-- ---------------------------------------------------------------------------
-- STEP 04. 온라인 DB 연동하기
--
-- Supabase 프로젝트 생성 후, 왼쪽 메뉴의 SQL Editor에 이 파일 내용을
-- 그대로 붙여넣고 Run을 누르면 progress 테이블이 만들어집니다.
--
-- 3D 장면 속 사물을 클릭해서 단어를 익히거나(3D 모드), 문장 모드에서
-- "오늘 학습" 버튼을 누르면 이 테이블에 오늘 날짜로 기록이 남습니다.
-- hotspot_id 하나가 단어(desk, airplane 등)와 그 예문을 함께 가리키므로
-- 단어 학습과 문장 학습이 같은 테이블에 함께 쌓입니다.
-- ---------------------------------------------------------------------------

create table if not exists progress (
  id bigint generated by default as identity primary key,
  user_id text not null,
  hotspot_id text not null,
  studied_on date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists progress_user_id_idx on progress (user_id);
create index if not exists progress_studied_on_idx on progress (studied_on);

-- 로그인 기능 없이 브라우저에 저장된 임의 ID(user_id)로 기록을 구분합니다.
-- 그래서 누구나 읽고 쓸 수 있도록 정책을 열어둡니다. 실 서비스로 발전시킬
-- 때는 Supabase Auth로 로그인을 추가하고 user_id를 auth.uid()로 제한하세요.
alter table progress enable row level security;

create policy "anyone can insert progress"
  on progress for insert
  with check (true);

create policy "anyone can read progress"
  on progress for select
  using (true);
