-- ---------------------------------------------------------------------------
-- STEP 04. 온라인 DB 연동하기
--
-- Supabase 프로젝트 생성 후, 왼쪽 메뉴의 SQL Editor에 이 파일 내용을
-- 그대로 붙여넣고 Run을 누르면 explorer_progress 테이블이 만들어집니다.
--
-- 3D 장면 속 사물을 클릭해서 단어를 익히거나(3D 모드), 문장 모드에서
-- "오늘 학습" 버튼을 누르면 이 테이블에 오늘 날짜로 기록이 남습니다.
-- hotspot_id 하나가 단어(desk, airplane 등)와 그 예문을 함께 가리키므로
-- 단어 학습과 문장 학습이 같은 테이블에 함께 쌓입니다.
--
-- 테이블 이름을 progress가 아니라 explorer_progress로 둔 이유: 같은
-- Supabase 프로젝트를 "영어 학습 앱(문장 플래시카드 편)" 강의와 함께 쓸 경우
-- 그쪽 프로젝트가 이미 progress 테이블을 쓰고 있어 이름이 겹치기 때문입니다.
-- ---------------------------------------------------------------------------

create table if not exists explorer_progress (
  id bigint generated by default as identity primary key,
  user_id text not null,
  hotspot_id text not null,
  studied_on date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists explorer_progress_user_id_idx on explorer_progress (user_id);
create index if not exists explorer_progress_studied_on_idx on explorer_progress (studied_on);

-- 로그인 기능 없이 브라우저에 저장된 임의 ID(user_id)로 기록을 구분합니다.
-- 그래서 누구나 읽고 쓸 수 있도록 정책을 열어둡니다. 실 서비스로 발전시킬
-- 때는 Supabase Auth로 로그인을 추가하고 user_id를 auth.uid()로 제한하세요.
alter table explorer_progress enable row level security;

create policy "anyone can insert explorer_progress"
  on explorer_progress for insert
  with check (true);

create policy "anyone can read explorer_progress"
  on explorer_progress for select
  using (true);
