-- 기존 3D 탐험 학습 기록 테이블
-- 기존 강의 실습과의 호환을 위해 유지합니다.
create table if not exists explorer_progress (
  id bigint generated by default as identity primary key,
  user_id text not null,
  hotspot_id text not null,
  studied_on date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists explorer_progress_user_id_idx on explorer_progress (user_id);
create index if not exists explorer_progress_studied_on_idx on explorer_progress (studied_on);
alter table explorer_progress enable row level security;

-- 기존 체험 모드 정책은 로그인 없는 예전 강의 실습을 위해 유지합니다.
drop policy if exists "anyone can insert explorer_progress" on explorer_progress;
drop policy if exists "anyone can read explorer_progress" on explorer_progress;
create policy "legacy progress insert" on explorer_progress for insert with check (true);
create policy "legacy progress read" on explorer_progress for select using (true);

-- 고도화 버전: 인증 사용자의 항목별 적응형 복습 상태
create table if not exists explorer_review_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null,
  due_at timestamptz not null default now(),
  interval_days numeric not null default 0,
  ease_factor numeric not null default 2.5,
  repetitions integer not null default 0,
  lapses integer not null default 0,
  last_rating text check (last_rating in ('again', 'hard', 'good', 'easy')),
  updated_at timestamptz not null default now(),
  primary key (user_id, item_id)
);

create index if not exists explorer_review_due_idx on explorer_review_state (user_id, due_at);
alter table explorer_review_state enable row level security;
drop policy if exists "review own select" on explorer_review_state;
drop policy if exists "review own insert" on explorer_review_state;
drop policy if exists "review own update" on explorer_review_state;
create policy "review own select" on explorer_review_state for select using (auth.uid() = user_id);
create policy "review own insert" on explorer_review_state for insert with check (auth.uid() = user_id);
create policy "review own update" on explorer_review_state for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 복습 이벤트는 점수·학습 분석·향후 대시보드에 사용합니다.
create table if not exists explorer_review_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null,
  rating text not null check (rating in ('again', 'hard', 'good', 'easy')),
  created_at timestamptz not null default now()
);

create index if not exists explorer_review_events_user_idx on explorer_review_events (user_id, created_at desc);
alter table explorer_review_events enable row level security;
drop policy if exists "events own select" on explorer_review_events;
drop policy if exists "events own insert" on explorer_review_events;
create policy "events own select" on explorer_review_events for select using (auth.uid() = user_id);
create policy "events own insert" on explorer_review_events for insert with check (auth.uid() = user_id);

-- Supabase 대시보드 Authentication에서 Email OTP/Magic Link와 Google provider를 켜고,
-- Site URL 및 Redirect URL에 배포 주소를 등록해야 합니다.
